name: Metrics
on:
  # Roda todo dia meia-noite
  schedule: [{cron: "0 0 * * *"}]
  # Permite rodar manualmente
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Seu token secreto
          token: ${{ secrets.METRICS_TOKEN }}

          # Opções principais
          user: Deutschh
          template: classic
          base: "" # Deixa vazio para focar só na cidade
          config_timezone: America/Sao_Paulo
          
          # A CIDADE 3D (Isocalendar)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year # Mostra o ano todo
          
          # Cores e Tema (Dark Mode Roxo)
          config_style: |
            .calendar-graph text.month { fill: #ffffff !important; }
            .calendar-graph text.wday { fill: #ffffff !important; }
