name: GitHub-Profile-3D-Contrib 

on:
  schedule: # Agendamento (Cron Job)
    - cron: "0 18 * * *" # Significa: "Rode todo dia às 18h UTC"
  workflow_dispatch: # Permite que você rode manualmente clicando num botão (bom para testar)

jobs:
  build:
    runs-on: ubuntu-latest # O robô vai usar uma máquina virtual Linux (Ubuntu)
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3 # Passo 1: O robô baixa o seu código atual
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1 # Passo 2: Roda o script pronto dessa pessoa (yoshi389111)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Dá permissão pro robô ler seus dados
          USERNAME: ${{ github.repository_owner }} # Pega seu nome de usuário automaticamente
      
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated"
          git push
