name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          # AQUI ESTÁ A MÁGICA DAS SUAS CORES:
          SETTING_JSON: |
            {
                "backgroundColor": "#0d1117",
                "foregroundColor": "#ffffff",
                "strongColor": "#ff00ff",
                "weakColor": "#161b22",
                "radarColor": "#00ff00",
                "gradeColors": [
                  "#161b22",
                  "#0e4429",
                  "#2ea043",
                  "#8a2be2",
                  "#d2a8ff"
                ]
            }
      
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated custom colors"
          git push
